version: "3.6"
services:
  gluetun:
    image: "qmcgaw/gluetun:latest"
    container_name: "gluetun"
    hostname: "gluetun"
    cap_add:
      - "NET_ADMIN"    
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: 10.64.115.253/32
      PUID: 1001
      PGID: 1002
      UMASK: 002
      TZ: America/Denver
    networks:
      - arrnet  
    ports:
      - "6881:6881/tcp" #qBittorrent
      - "6881:6881/udp" #qBittorrent
      - "8080:8080/tcp" #SABnzb
      - "8090:8090/tcp" #qBittorrent
    restart: always
      
  JellyFin:
    image: "jellyfin/jellyfin:latest"
    container_name: "jellyfin"
    hostname: "jellyfin"
    environment:
      - "PUID=1002"
      - "PGID=1002"
      - "UMASK=002"  
      - "TZ=America/Denver"       
    networks:
      - arrnet  
    ports:
      - "8096:8096/tcp"
    volumes:
      - "/mnt/media/data/media:/media:ro"
      - "jellyfin_cache:/cache"
      - "jellyfin_config:/config"
    restart: unless-stopped
      
  SABnzb:
    image: "linuxserver/sabnzbd:latest"
    container_name: "sabnzb"
    environment:
      - "PUID=1003"
      - "PGID=1002"
      - "UMASK=002" 
      - "TZ=America/Denver"       
    network_mode: "service:gluetun"
    volumes:
      - "/mnt/media/data:/data"
      - "sabnzb_config:/config"  
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    
  qBittorrent:
    image: "linuxserver/qbittorrent:latest"
    container_name: "qbittorrent"
    environment:
      - "WEBUI_PORT=8090"
      - "PUID=1004"
      - "PGID=1002"
      - "UMASK=002"   
      - "TZ=America/Denver"      
    network_mode: "service:gluetun"
    volumes:
      - "/data:/mnt/media/data"
      - "qbittorrent_config:/config"
    restart: unless-stopped
    depends_on:
      gluetun:
          condition: service_healthy
  prowlarr:
    image: "linuxserver/prowlarr:latest"
    container_name: "prowlarr"
    environment:
      - "PUID=1005"
      - "PGID=1002"
      - "UMASK=002"    
    networks:
      - arrnet  
    ports:
      - "9696:9696/tcp"
    volumes:
      - "prowlarr_config:/config"
    restart: unless-stopped

  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: "sonarr"
    environment:
      - "PUID=1006"
      - "PGID=1002"
      - "UMASK=002"
      - "TZ=America/Denver"
    networks:
      - arrnet  
    ports:
      - "8989:8989/tcp"
    volumes:
      - "/mnt/media/data:/data"
      - "sonarr_config:/config"
    restart: unless-stopped

  radarr:
    image: "linuxserver/radarr:latest"
    container_name: "radarr"
    environment:
      - "PUID=1007"
      - "PGID=1002"
      - "UMASK=002"
      - "TZ=America/Denver"
    networks:
      - arrnet  
    ports:
      - "7878:7878/tcp"
    volumes:
      - "/mnt/media/data:/data"
      - "radarr_config:/config"
    restart: unless-stopped
    
  bazarr:
    image: "linuxserver/bazarr"
    container_name: bazarr
    environment:
      - "PUID=1008"
      - "PGID=1002"
      - "UMASK=002"
      - "TZ=America/Denver"
    volumes:
      - "/mnt/media/data:/data"
      - "bazarr_config:/config"
    networks:
      - arrnet  
    ports:
      - "6767:6767/tcp"
    restart: unless-stopped    
    
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - arrnet  
volumes:
  jellyfin_cache:
    external: true
  jellyfin_config:
    external: true
  sabnzb_config:
    external: true
  qbittorrent_config:
    external: true
  prowlarr_config:
    external: true
  sonarr_config:
    external: true
  radarr_config:
    external: true
  bazarr_config:
    external: true
networks:
  arrnet:
